server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/chrywhy/test
          #username: admin
          #password: 123456
          searchPaths: spring-cloud/helloworldConfig

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1089/eureka/

